### ISSUE TITLE
[feat] setBtnHomeGoReminderClickListener

### ISSUE THREAD

**Issue by kym1924** [TeamKeepin/keepin-android#116]
# 📝 DESCRIPTION
### setBtnHomeGoReminderClickListener()
# ☑️ TODO
- [x] Add navigation Action
- [x] Update setBtnHomeGoReminderClickListener() in HomeFragment
- [x] Delete setBtnHomeGoReminderClickListener() in MainActivity
