### ISSUE TITLE
[feat] SignUpFirstFragment Feature

### ISSUE THREAD

**Issue by kym1924** [TeamKeepin/keepin-android#143]
# 📝 DESCRIPTION
### SignUpFirstFragment Feature
# ☑️ TODO
- [x] Create SignUpViewModel
- [x] Setting EditText Background
- [x] Setting Delete Button Visibility
- [x] Setting Warning Text Visibility
- [x] Setting Confirm Text Text Color and Clickable
- [x] Create String Resources
- [x] Update auth_nav_graph
