### ISSUE TITLE
[feat] SignUpSecondFragment Feature

### ISSUE THREAD

**Issue by kym1924** [TeamKeepin/keepin-android#151]
# 📝 DESCRIPTION
### SignUpSecondFragment Feature
# ☑️ TODO
- [x] Update SignUpViewModel
- [x] Update fragment_sign_up_second.xml
- [x] Update fragment_sign_up_first.xml
- [x] Setting EditText Background
- [x] Setting Delete Button Visibility
- [x] Setting Confirm Text Text Color and Clickable
- [x] Create String Resources
- [x] Update auth_nav_graph
