### ISSUE TITLE
[feat] MyPageFriendsAdapter

### ISSUE THREAD

**Issue by kym1924** [TeamKeepin/keepin-android#160]
# 📝 DESCRIPTION
### MyPageFriendsAdapter
# ☑️ TODO
- [x] Create MyPageViewModel
- [x] Create MyPageFriendsAdapter
- [x] Create data class
- [x] Update item_my_page_friend.xml
- [x] Update nav_graph.xml
