### ISSUE TITLE
[feat] FriendDetailFragment Data Binding

### ISSUE THREAD

**Issue by kym1924** [TeamKeepin/keepin-android#164]
# 📝 DESCRIPTION
### FriendDetailFragment Data Binding
# ☑️ TODO
- [x] Create setTvNicknameText()
- [x] Create setFriendDetailObserve()
- [x] Create val friendDetail in FriendViewModel
- [x] Create data class
- [x] Create String Resources
- [x] Update setTvFriendMemoLinesText()
- [x] Update MyPageFriendsAdapter for name
- [x] Update nav_graph.xml
