### ISSUE TITLE
[layout] NameUpdateFragment and Refactoring FriendUpdateFragment

### ISSUE THREAD

**Issue by kym1924** [TeamKeepin/keepin-android#179]
# 📝 DESCRIPTION
### NameUpdateFragment and Refactoring
# ☑️ TODO
- [x] Create ProfileViewModel
- [x] Create NameUpdateFragment
- [x] Layout NameUpdateFragment
- [x] Create setLayoutNameClickListener() in ProfileFragment
- [x] Refactoring FriendUpdateFragment for Data Binding
- [x] Update nav_graph.xml
- [x] Create String Resources
