### ISSUE TITLE
[feat] Coming Reminder in HomeFragment

### ISSUE THREAD

**Issue by kym1924** [TeamKeepin/keepin-android#188]
# 📝 DESCRIPTION
### Coming Reminders in HomeFragment
# ☑️ TODO
- [x] Create HomeViewModel
- [x] Create Data Class
- [x] Refactor SerializedName
- [x] Data Binding HomeFragment
- [x] Refactor MyPageFriendsAdapter Delete inner class
