### ISSUE TITLE
[fix] Apply Ktlint

### ISSUE THREAD

**Issue by kym1924** [TeamKeepin/keepin-android#19]
# 📝 DESCRIPTION
### Apply Ktlint
# ☑️ TODO
- [x] Add String Resource for Binding Error
- [x] Add Blank Line for ktlint
- [x] Add buildFeatures in Gradle for Binding
- [x] Modify Binding Layout in Fragments
