### ISSUE TITLE
[layout] Layout BaseDialog

### ISSUE THREAD

**Issue by yjooooo** [TeamKeepin/keepin-android#190]
# 📝 DESCRIPTION
### Layout BaseDialog
# ☑️ TODO
- [x] dialog_base.xml
- [x] strings.xml
- [x] nav_graph.xml
- [x] border_white_fill_10
