### ISSUE TITLE
[feat] PasswordUpdateFragment Warning Visibility

### ISSUE THREAD

**Issue by kym1924** [TeamKeepin/keepin-android#221]
# 📝 DESCRIPTION
### PasswordUpdateFragment Warning Visibility
# ☑️ TODO
- [x] Create Logic about Warning
- [x] Data Binding PasswordUpdateFragment
- [x] Create Color Resource for red
- [x] Apply color Resource
