### ISSUE TITLE
[layout] ReminderFragment

### ISSUE THREAD

**Issue by yjooooo** [TeamKeepin/keepin-android#27]
# 📝 DESCRIPTION
### Layout ReminderFragment
# ☑️ TODO
- [x] fragment_reminder.xml
- [x] item_reminder_month.xml
- [x] item_reminder_event.xml
- [x] selector_reminder_switch_track.xml
- [x] selector_reminder_switch_thumb.xml
- [x] selector_reminder_radio_btn.xml
- [x] border_black_fill_28.xml
- [x] border_green_line_circle.xml
- [x] border_gray_line_circle.xml
- [x] border_gray_fill_switch_20.xml
- [x] border_green_fill_switch_20.xml
