### ISSUE TITLE
[feat] Glide placeholder

### ISSUE THREAD

**Issue by kym1924** [TeamKeepin/keepin-android#318]
# 📝 DESCRIPTION
### Setting Glide placeholder
# ☑️ TODO
- [x] ImageView.glide(url: String)
- [x] Delete temp Image
- [x] Delete Object ImageGlide
