### ISSUE TITLE
[feat] Splash Animation

### ISSUE THREAD

**Issue by kym1924** [TeamKeepin/keepin-android#343]
# 📝 DESCRIPTION
### Splash Animation
# ☑️ TODO
- [x] Delete SignInMainFragment
- [x] Create Setting Animation for logo
- [x] Delete Unused Resources
- [x] Update strings.xml
- [x] Update auth_nav_graph.xml
