### ISSUE TITLE
[feat] PopupMenu in FriendDetailFragment

### ISSUE THREAD

**Issue by kym1924** [TeamKeepin/keepin-android#88]
# 📝 DESCRIPTION
### PopupMenu in FriendDetailFragment
# ☑️ TODO
- [x] Create menu item
- [x] Create String Resources
- [x] Create Style Resource for Popup Menu Text
- [x] setBtnFriendDetailOptionClickListener()
