### ISSUE TITLE
[refactor] Remove KeepInViewActivity

### ISSUE THREAD

**Issue by gaeun23** [TeamKeepin/keepin-android#99]
# 📝 DESCRIPTION
### Remove KeepInView Activity 
# ☑️ TODO
- [x] Remove KeepInActivity.kt
- [x] Remove activity_keep_in.xml
- [x] Remove FriendSearchActivity.kt
- [x] Remove activity_friend_search.xml
